WITH CTE AS 
(SELECT
FORMAT(PAY_DATE,'yyyy-MM') AS pay_month
,E.DEPARTMENT_ID
,AVG(AMOUNT) OVER(PARTITION BY FORMAT(PAY_DATE,'yyyy-MM'),E.DEPARTMENT_ID ) AS DEP_AVG
,AVG(AMOUNT) OVER(PARTITION BY FORMAT(PAY_DATE,'yyyy-MM') ) AS COMPANY_AVG
FROM SALARY S JOIN EMPLOYEE E
    ON S.EMPLOYEE_ID = E.EMPLOYEE_ID)

-- SELECT  FROM CTE;

SELECT
DISTINCT pay_month
,DEPARTMENT_ID as department_id
,CASE 
    WHEN DEP_AVG > COMPANY_AVG THEN 'higher'
    WHEN DEP_AVG < COMPANY_AVG THEN 'lower'
    else 'same'
end as comparison
FROM CTE
order by pay_month desc
